version: "2"

services:
  worker:
    build: .
    command: memorious process
    links:
      - redis
    volumes:
      - "./build/data:/data"
    tmpfs:
      - "/tmp"

  ui:
    build: .
    command: gunicorn -t 900 -w 8 -b 0.0.0.0:8000 --log-level info --log-file - memorious.ui:app
    links:
      - redis
    volumes:
      - "./build/data:/data"
    tmpfs:
      - "/tmp"
    ports:
      - "8000:8000"

  beat:
    build: .
    command: memorious scheduled --wait
    links:
      - redis
    volumes:
      - "./build/data:/data"
    tmpfs:
      - "/tmp"

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./build/redis-data:/data
