# Scraper for the OCCRP web site.
# The goal is not to download all HTML, but only PDFs & other documents
# linked from the page as proof.
name: kg_akipress_headers

# A title for display in the UI:
description: 'Headers from articles on akipress.kg'

# Uncomment to run this scraper automatically:
schedule: monthly
delay: 1
stealthy: true
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: seed
    params:
      urls:
        - http://svodka.akipress.org/
        - http://www.turmush.kg/
        
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    params:
      # These rules specify which pages should be scraped or included:
      rules:
        or:
          - pattern: 'http://svodka.akipress.org/news/'
          - pattern: 'http://www.turmush.kg/ru/news/'
          - pattern: 'http://www.turmush.kg/news/'
          - pattern: 'http://svodka.akipress.org/$'
          - pattern: 'http://www.turmush.kg/$'
    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: parse
    params:
      store:
        and:
          - pattern: 'http://svodka.akipress.org/news/'
          - pattern: 'http://www.turmush.kg/ru/news/'
          - pattern: 'http://www.turmush.kg/news/'
         
          
    handle:
      # this makes it a recursive web crawler:
      store: extractdata
      fetch: fetch
  
  extractdata:
    # Parse the scraped pages to extract useful information
    method: example.akipress_headers:extractdata
    handle:
      pass: store

  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "kg_akipress_headers"
      unique:
        - url