# Scraper for the OCCRP web site.
# The goal is not to download all HTML, but only PDFs & other documents
# linked from the page as proof.
name: kg_grs

# A title for display in the UI:
description: 'Grs of Kyrgyz Republic'

# Uncomment to run this scraper automatically:
schedule: daily
delay: 1
stealthy: true
pipeline:


  init:
    # This first stage will get the ball rolling with a seed URL.
    method: seed
    params:
      urls:
        - http://address.darek.gosreg.kg/search/street/6202?streetType=0&streetName=&filter=sort
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    params:
      # These rules specify which pages should be scraped or included:
      rules:
        and:
          - domain: http://address.darek.gosreg.kg/
    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: parse
    handle:
      # this makes it a recursive web crawler:
      store: extractdata
      fetch: fetch
  
  extractdata:
    # Parse the scraped pages to extract useful information
    method: example.kg_grs:extractdata
    handle:
      pass: store


  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "kg_grs"
        